services:
  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    volumes:
      - ./backend:/app
    networks:
      - net_hub
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env 
    healthcheck:
      test: ["CMD","curl","-f","http://backend:8000"]
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 10s     


  frontend:
    build: ./frontend
    container_name: frontend_service
    restart: always
    volumes:
      - ./frontend:/app
    networks:
      - net_hub
    ports:
      - "3000:3000"


  mongo_db:
    image: mongo:6
    container_name: mongo_db_service
    restart: always
    volumes:
      - mongo_data:/app
    networks:
      - net_hub
    healthcheck:
      test: ["CMD","mongosh","--eval","db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 10s


volumes:
  mongo_data:
networks:
  net_hub:                